import { useState } from "react";

import Head from "next/head";
import NavBar from "@/components/navBar";
import Hero from "@/components/hero";
import PokemonColors from "@/components/pokemonColors";
import Footer from "@/components/footer";

import styles from "@/styles/Home.module.scss";

export default function Home() {
  const [backGroundImg, setBackgroundImg] = useState("");

  const handleBackgroundChange = (imageUrl) => {
    setBackgroundImg(imageUrl);
  };
  return (
    <>
      <Head>
        <title>Code Week - Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <NavBar />
        <div
          className={styles.bgImage}
          style={{
            width: "100%",
            backgroundImage: `url(${backGroundImg})`,
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            backgroundPosition: "center",
          }}
        >
          <Hero />
          <div className={styles.blackBand}></div>
          <PokemonColors onCardClick={handleBackgroundChange} />
        </div>
        <Footer />
      </main>
    </>
  );
}
